on: ["pull_request"]

name: Test Coveralls

jobs:

  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:  

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - run: flutter test --coverage
          
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
            
